! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null

minecraft:badlands > minecraft:desert
minecraft:eroded_badlands > minecraft:desert
minecraft:wooded_badlands > minecraft:desert
minecraft:dark_forest > minecraft:forest
minecraft:snowy_beach > minecraft:snowy_plains
minecraft:grove > minecraft:snowy_plains

wetland_whimsy:marsh > minecraft:swamp