! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null

minecraft:badlands > minecraft:desert
minecraft:eroded_badlands > minecraft:desert
minecraft:wooded_badlands > minecraft:desert
minecraft:dark_forest > minecraft:pale_garden
minecraft:sunflower_plains > minecraft:plains
minecraft:cherry_grove > environmental:blossom_woods
minecraft:snowy_beach > minecraft:snowy_plains

minecraft:pale_garden > null 
minecraft:snowy_beach > null
minecraft:grove > null

environmental:marsh > null

atmospheric:scrubland > null
atmospheric:kousa_jungle > null
atmospheric:snowy_scrubland > null
atmospheric:spiny_thicket > null

windswept:lavender_fields > null

bf_biomes:baobab_forest > null
bf_biomes:ginkgo_forest > null
bf_biomes:maple_forest > minecraft:forest

wetland_whimsy:marsh > null

environmental:pine_barrens > natures_spirit:redwood_forest

biomeswevegone:araucaria_savanna > bf_biomes:baobab_forest
biomeswevegone:baobab_savanna > bf_biomes:baobab_forest
biomeswevegone:orchard > windswept:lavender_fields