
[region]
	#Range: > 0
	terra_ferax_weight = 5
	#Range: > 0
	terra_solaris_weight = 5
	#Range: > 0
	terra_flava_weight = 5
	#Range: > 0
	terra_laeta_weight = 5
	#Range: > 0
	terra_mater_weight = 5

[misc]
	calcite_generator = true
	deepslate_generator = true
	creative_tab = true
	sugi_and_stratified_pillars = true

[datapack]
	vanilla_trees_toggle = false
	birch_forest_toggle = false
	flower_forest_toggle = true
	jungle_toggle = false
	swamp_toggle = false
	desert_toggle = false
	badlands_toggle = true
	mountain_biomes_toggle = true
	savanna_toggle = true
	dark_forest_toggle = true
	windswept_hills_toggle = true

[biome]
	has_sugi_forest = false
	has_windswept_sugi_forest = false
	has_blooming_sugi_forest = false
	has_lavender_fields = false
	has_marsh = true
	has_bamboo_wetlands = true
	has_wisteria_forest = true
	has_redwood_forest = true
	has_snowy_redwood_forest = true
	has_aspen_forest = false
	has_maple_woodlands = true
	has_golden_wilds = true
	has_marigold_meadows = true
	has_fir_forest = true
	has_snowy_fir_forest = true
	has_cypress_fields = false
	has_cedar_thicket = true
	has_carnation_fields = false
	has_stratified_desert = false
	has_blooming_dunes = false
	has_lively_dunes = false
	has_drylands = false
	has_wooded_drylands = false
	has_xeric_plains = false
	has_white_cliffs = true
	has_prairie = true
	has_oak_savanna = false
	has_heather_fields = true
	has_tundra = true
	has_alpine_clearings = true
	has_alpine_highlands = true
	has_coniferous_covert = true
	has_boreal_taiga = true
	has_tropical_shores = false
	has_tropical_woods = true
	has_sparse_tropical_woods = false
	has_tropical_basin = true
	has_arid_savanna = true
	has_scorched_dunes = false
	has_flowering_shrubland = true
	has_shrubland = false
	has_arid_highlands = false
	has_shrubby_highlands = false
	has_woody_highlands = false
	has_red_peaks = false
	has_dusty_slopes = false
	has_snowcapped_red_peaks = false
	has_sleeted_slopes = true
	has_blooming_highlands = true
	has_chaparral = false
	has_floral_ridges = true

