#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 13 01:15:46 GMT+04:00 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=20
shaderPack=
enableShaders=false
