#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 10 22:35:35 GMT+04:00 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
