#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 14 18:39:53 GMT+04:00 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=20
shaderPack=
enableShaders=false
