#Indigo properties file
<<<<<<< HEAD
#Sat May 02 21:30:12 GMT+04:00 2026
=======
#Fri Apr 24 23:36:25 GMT+04:00 2026
>>>>>>> bf9d29105cc81c5ec88530d6528ae32a72acdfdb
fix-mean-light-calculation=auto
debug-compare-lighting=auto
fix-exterior-vertex-lighting=auto
ambient-occlusion-mode=hybrid
always-tesselate-blocks=auto
fix-smooth-lighting-offset=auto
fix-luminous-block-ambient-occlusion=auto
